# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='contetn',
            new_name='content',
        ),
    ]
