# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 22:33
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170515_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('thumbnail', models.URLField(max_length=100, verbose_name='\u7f29\u7565\u56fe')),
                ('link_to', models.URLField(max_length=100, verbose_name='\u8df3\u8f6c\u5230')),
                ('index', models.SmallIntegerField(unique=True, verbose_name='\u4f4d\u7f6e')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='\u5185\u5bb9'),
        ),
    ]
