# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfz_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dfzuser',
            options={'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237'},
        ),
    ]
