# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfz_auth', '0002_auto_20170511_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dfzuser',
            options={'verbose_name': '\u540e\u53f0\u7528\u6237', 'verbose_name_plural': '\u540e\u53f0\u7528\u6237'},
        ),
    ]
