# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('thumbnail', models.URLField(verbose_name='\u7f29\u7565\u56fe')),
                ('video_url', models.URLField(verbose_name='\u89c6\u9891\u5730\u5740')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('profile', models.TextField(verbose_name='\u8bfe\u7a0b\u7b80\u4ecb')),
                ('audience', models.TextField(null=True, verbose_name='\u9002\u5b9c\u4eba\u7fa4')),
                ('price', models.FloatField(default=0, verbose_name='\u4ef7\u683c')),
                ('duration', models.FloatField(verbose_name='\u65f6\u957f(\u5206)')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u5206\u7c7b',
                'verbose_name_plural': '\u8bfe\u7a0b\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='SeriesCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('price', models.FloatField(default=0, verbose_name='\u4ef7\u683c')),
                ('duration', models.FloatField(null=True, verbose_name='\u65f6\u957f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('course_num', models.IntegerField(null=True, verbose_name='\u8bfe\u7a0b\u6570\u91cf')),
            ],
            options={
                'verbose_name': '\u7cfb\u5217\u8bfe\u7a0b',
                'verbose_name_plural': '\u7cfb\u5217\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bb2\u5e08\u540d')),
                ('identity', models.CharField(max_length=100, verbose_name='\u8eab\u4efd')),
                ('profile', models.TextField(null=True, verbose_name='\u7b80\u4ecb')),
                ('avatar', models.URLField(verbose_name='\u5934\u50cf\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u8bb2\u5e08',
                'verbose_name_plural': '\u8bb2\u5e08',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8d2d\u4e70\u8bfe\u7a0b\u8bb0\u5f55',
                'verbose_name_plural': '\u8d2d\u4e70\u8bfe\u7a0b\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='UserSeriesCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('series_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.SeriesCourse', verbose_name='\u7cfb\u5217\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u8d2d\u4e70\u7cfb\u5217\u8bfe\u7a0b\u8bb0\u5f55',
                'verbose_name_plural': '\u8d2d\u4e70\u7cfb\u5217\u8bfe\u7a0b\u8bb0\u5f55',
            },
        ),
    ]
