# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 14:11
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170511_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='audience',
            field=models.TextField(blank=True, null=True, verbose_name='\u9002\u5b9c\u4eba\u7fa4'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u7b80\u4ecb'),
        ),
    ]
