# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 03:01
from __future__ import unicode_literals

import DjangoQiniu.models
import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170511_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='audience',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u9002\u5b9c\u4eba\u7fa4'),
        ),
        migrations.AlterField(
            model_name='course',
            name='profile',
            field=DjangoUeditor.models.UEditorField(verbose_name='\u8bfe\u7a0b\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=DjangoQiniu.models.QiniuField(btn_title='\u4e0a\u4f20\u6587\u4ef6', qiniu_field='video_url', verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
