# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 03:42
from __future__ import unicode_literals

import DjangoQiniu.models
import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20170515_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outline',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u8bfe\u7a0b\u5927\u7eb2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=DjangoQiniu.models.QiniuField(btn_title='\u4e0a\u4f20\u6587\u4ef6', qiniu_field='thumbnail', verbose_name='\u7f29\u7565\u56fe'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=DjangoQiniu.models.QiniuField(btn_title='\u4e0a\u4f20\u6587\u4ef6', qiniu_field='avatar', verbose_name='\u5934\u50cf\u5730\u5740'),
        ),
    ]
