# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20170515_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=10, verbose_name='\u65f6\u957f'),
        ),
    ]
