# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=11)),
                ('_password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '\u524d\u53f0\u7528\u6237',
                'verbose_name_plural': '\u524d\u53f0\u7528\u6237',
            },
        ),
    ]
